# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1103, 842)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.emergency = QtWidgets.QPushButton(self.centralwidget)
        self.emergency.setGeometry(QtCore.QRect(140, 480, 201, 271))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.emergency.setFont(font)
        self.emergency.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.emergency.setObjectName("emergency")
        self.state_title = QtWidgets.QLabel(self.centralwidget)
        self.state_title.setGeometry(QtCore.QRect(20, 30, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.state_title.setFont(font)
        self.state_title.setStyleSheet("background-color: rgb(0, 255, 127);\n"
"background-color: rgb(91, 91, 91);")
        self.state_title.setScaledContents(False)
        self.state_title.setAlignment(QtCore.Qt.AlignCenter)
        self.state_title.setObjectName("state_title")
        self.state = QtWidgets.QLabel(self.centralwidget)
        self.state.setGeometry(QtCore.QRect(20, 90, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.state.setFont(font)
        self.state.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.state.setScaledContents(False)
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.plotWidget = QtWidgets.QWidget(self.centralwidget)
        self.plotWidget.setGeometry(QtCore.QRect(600, 109, 461, 581))
        self.plotWidget.setObjectName("plotWiget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1103, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.emergency.setText(_translate("MainWindow", "Emergency"))
        self.state_title.setText(_translate("MainWindow", "Robot_State"))
        self.state.setText(_translate("MainWindow", "No_State"))
